### PR TITLE
Fixed small bug in queue_entry

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi,

Found this small bug when I did some tests

Cheers,
Marcus

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Currently sample_view.shapes is not implemented in the QtGraphicsManager. Could we wait a bit with this PR?

**Comment by marcus-oscarsson** [comment]
Hm, Its a bit complicated since a change made a few PR's back changed from passing shapes to passing sample_view, and this unfortunately brakes things for us as its two separate objects.So we needs this change for things to work. I thought that there was a temporary solution put in place to point .shapes to self by @rhfogh ? I would maybe suggest to put that back and then try to find a common way to do this ?

**Comment by marcus-oscarsson** [comment]
Or if you have another idea to solve the problem :)

**Comment by marcus-oscarsson** [comment]
@IvarsKarpics I was going to start to look at the SampleView would you like to discuss it before i start ?

**Comment by marcus-oscarsson** [comment]
Superseded by #546

**Pull request closed without merging**
