### PR TITLE
Added missing update_values functions to abstract classes

### PR DESCRIPTION
**Pull request by rhfogh**
Added missing AbstractActuator.update_values and AbstractNState,update_values

### CODE REVIEW

**Comment by beteva** [comment]
Hello @rhfogh. I see you've been quite busy during the week-end. Just a question - didn't we say we change the name update_values to something else?

**Comment by marcus-oscarsson** [comment]
I guess we can discuss the name in another ISSUE or PR if needed, this looks good to me :)

**Comment by rhfogh** [comment]
@beteva 
We did discuss changing the name, and I think we shall, but I am not sure what name we agreed on. So I left it there for now. Once we have the name I can fix it in a jiffy.

**Comment by marcus-oscarsson** [comment]
@rfogh I don't know what happened with this PR, it looked fine a day or so a go but it look like there are some of our commits added on top, what happened ?

Your changes still looks fine to me :)

**Comment by rhfogh** [comment]
@marcus-oscarsson I tried to merge it with the new master and push the result, but I seem to be getting some kind of confusion when i try that.

What is the normal proecdure - who is reponsible for merging updates to master into existing PRs? And it it (normally) done directly on github, or locally and then pushed?

**Comment by rhfogh** [comment]
SUperseded by #539  (same content but cleaner commit history)

**Pull request closed without merging**
