### PR TITLE
WIP Hwr repository rename

### PR DESCRIPTION
**Pull request by rhfogh**
Renamed HardwareRepository and HardwareObjects. 
It was not too hard, since the vast majoarity of references was in imort statements.

Comments:

- Rename is to mx3core. This is not to pre-empt the choice but just to have something to work with. We can get whatever name we want by a simple gobal replace.
- 
- The following has *not* been changed:
    - HardwareRepository.xml/
    - References to HardwareRepository.py
    - *.md documentation files
    - URLs
    - edna config file paths
    - Comments referring to the HardwareRepository submodule

NB I have *not* actually renamed the HardwareRepository directory!!!
This is because renaming the top directory in the git repository throws git into a tizzy. For testing you can put in a softlink linking mx3core to HardwareRepository. Finishing this task will require interaction with the submodule setup, which is not my forte.

NB I have *not* tested this, since I do not have a functional setup for the master branch. Could someone else take over here?

As regards HardwareObjects, the renaming to hardware_objects was straightforward. A simple global search for HardwareObjects will show what has been left untouched.

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Hi @rhfogh 

Thanks again for getting this done so quickly !

Is not the problem that there is no mx3core module ?. How about creating a module called mx3core in the root and then move all .py files to this module and keep the rest in the root along with the mx3core module ? 

Or did you mean to make this in a separate step and this was just to be able to test ?

Marcus

**Comment by rhfogh** [comment]
@marcus-oscarsson 
This was just to be able to test. I tried renaming HardwareRepository to mx3core/ but then git did not work properly. I concluded that you cannot rename the repository (possibly because it is a submodule) without breaking things (or, of course, that I did not know the right way to do it), and the full change should be done together with changing the submodule and repository structure. Which was not on my TODO list and I gladly leave it to you.

**Comment by marcus-oscarsson** [comment]
Sounds good, let's have a look at that after the holidays then

**Comment by marcus-oscarsson** [comment]
@rhfogh do you think you can rebase this on master (I think it will resolve the conflicts automatically). I can try to make a new PR to your fork but that might require a force push on your side then. Let me know what you prefer ?

**Comment by marcus-oscarsson** [comment]
Perfect, thanks !

**Comment by rhfogh** [comment]
OK, I have now renamed all occurrences of 'mx3core' to 'mxcubecore'.
1) The comments above relative to file structure still apply - I did not adventure into renaming the top level repository.
2) since the to level directory HardwareRepository/mx3core was renamed (to HardwareRepository/mxcubecore), lots and lots of files appear as deleted and readded.
Still, this ought to be what we want to carry on from

**Comment by marcus-oscarsson** [comment]
@rhfogh by the way how did you do the rename with, `git mv` or simply with `mv` ?

**Comment by rhfogh** [comment]
@marcus-oscarsson The last oen here was with git (through pycharm). The original one I must admit I do ot remember.

**Comment by marcus-oscarsson** [comment]
@rhfogh ok, isee

**Comment by marcus-oscarsson** [comment]
To be done for the mxcubecore repository instead

**Pull request closed without merging**
