### PR TITLE
Implementation of abstract processing

### PR DESCRIPTION
**Pull request by IvarsKarpics**

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 31
           

Complexity increasing per file
==============================
- HardwareObjects/mockup/OfflineProcessingMockup.py  9
- HardwareObjects/queue_model_objects.py  1
- HardwareObjects/EMBL/EMBLResolution.py  1
- HardwareObjects/abstract/AbstractOnlineProcessing.py  21
- HardwareObjects/mockup/OnlineProcessingMockup.py  12
- HardwareObjects/EMBL/EMBLTransmission.py  4
         

Clones added
============
- HardwareObjects/mockup/OfflineProcessingMockup.py  5
- HardwareObjects/abstract/AbstractOnlineProcessing.py  3
- HardwareObjects/EMBL/EMBLTransmission.py  1
         

Clones removed
==============
+ HardwareObjects/queue_entry.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/HardwareRepository/pullRequest?prid=4656946&bid=15596374)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 27
           

Complexity increasing per file
==============================
- HardwareObjects/DozorOnlineProcessing.py  3
- HardwareObjects/abstract/AbstractOnlineProcessing.py  21
- HardwareObjects/mockup/OfflineProcessingMockup.py  9
- HardwareObjects/queue_model_objects.py  1
- HardwareObjects/mockup/OnlineProcessingMockup.py  12
- HardwareObjects/EMBL/EMBLTransmission.py  4
- HardwareObjects/EMBL/EMBLResolution.py  1
         

Clones added
============
- HardwareObjects/DozorOnlineProcessing.py  1
- HardwareObjects/abstract/AbstractOnlineProcessing.py  3
- HardwareObjects/mockup/OfflineProcessingMockup.py  5
- HardwareObjects/EMBL/EMBLTransmission.py  1
         

Clones removed
==============
+ HardwareObjects/queue_entry.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/HardwareRepository/pullRequest?prid=4656946&bid=15596374)

**Comment by IvarsKarpics** [comment]
Sorry, but few EMBL hwobj accidentally was added to this PR instead of previous PR (embl_update). I hope it is fine and one can accept them.

Ivars

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 24
           

Complexity increasing per file
==============================
- HardwareObjects/EMBL/EMBLResolution.py  1
- HardwareObjects/EMBL/EMBLTransmission.py  4
- HardwareObjects/mockup/OnlineProcessingMockup.py  12
- HardwareObjects/mockup/OfflineProcessingMockup.py  9
- HardwareObjects/abstract/AbstractOnlineProcessing.py  21
- HardwareObjects/queue_model_objects.py  1
- HardwareObjects/DozorOnlineProcessing.py  3
         

Clones added
============
- HardwareObjects/EMBL/EMBLTransmission.py  1
- HardwareObjects/mockup/OfflineProcessingMockup.py  4
- HardwareObjects/abstract/AbstractOnlineProcessing.py  3
- HardwareObjects/DozorOnlineProcessing.py  1
         

Clones removed
==============
+ HardwareObjects/queue_entry.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/HardwareRepository/pullRequest?prid=4656946&bid=15596374)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 26
           

Complexity increasing per file
==============================
- HardwareObjects/queue_model_objects.py  1
- HardwareObjects/EMBL/EMBLTransmission.py  4
- HardwareObjects/mockup/OnlineProcessingMockup.py  12
- HardwareObjects/EMBL/EMBLOnlineProcessing.py  7
- HardwareObjects/mockup/OfflineProcessingMockup.py  9
- HardwareObjects/abstract/AbstractOnlineProcessing.py  21
- HardwareObjects/EMBL/EMBLOfflineProcessing.py  9
- HardwareObjects/EMBL/EMBLResolution.py  1
- HardwareObjects/DozorOnlineProcessing.py  3
         

Clones added
============
- HardwareObjects/EMBL/EMBLTransmission.py  1
- HardwareObjects/EMBL/EMBLOnlineProcessing.py  2
- HardwareObjects/mockup/OfflineProcessingMockup.py  5
- HardwareObjects/abstract/AbstractOnlineProcessing.py  3
- HardwareObjects/EMBL/EMBLOfflineProcessing.py  5
- HardwareObjects/DozorOnlineProcessing.py  1
         

Clones removed
==============
+ HardwareObjects/queue_entry.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/HardwareRepository/pullRequest?prid=4656946&bid=15596374)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 26
           

Complexity increasing per file
==============================
- HardwareObjects/EMBL/EMBLResolution.py  1
- HardwareObjects/queue_model_objects.py  1
- HardwareObjects/mockup/OfflineProcessingMockup.py  9
- HardwareObjects/abstract/AbstractOnlineProcessing.py  21
- HardwareObjects/mockup/OnlineProcessingMockup.py  12
- HardwareObjects/EMBL/EMBLOnlineProcessing.py  7
- HardwareObjects/EMBL/EMBLOfflineProcessing.py  9
- HardwareObjects/EMBL/EMBLTransmission.py  4
- HardwareObjects/DozorOnlineProcessing.py  3
         

Clones added
============
- HardwareObjects/mockup/OfflineProcessingMockup.py  5
- HardwareObjects/abstract/AbstractOnlineProcessing.py  3
- HardwareObjects/EMBL/EMBLOnlineProcessing.py  2
- HardwareObjects/EMBL/EMBLOfflineProcessing.py  5
- HardwareObjects/EMBL/EMBLTransmission.py  1
- HardwareObjects/DozorOnlineProcessing.py  1
         

Clones removed
==============
+ HardwareObjects/queue_entry.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/HardwareRepository/pullRequest?prid=4656946&bid=15596374)

**Comment by marcus-oscarsson** [comment]
@IvarsKarpics, @all

What about creating a AbstractProcessing and if necessary create the sub-classes Online and OfflineProcessing ? Is there any need to make the separation between Offline or Online on the
abstract level ?

Its maybe a question for later and Ill in that case create another issue for it (if you agree) ?

Cheers,
Marcus

**Comment by marcus-oscarsson** [comment]
The discussion seems to have continued well in #452

**Comment by marcus-oscarsson** [comment]
@IvarsKarpics looks like there are a few conflicts to resolve

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 10
           

Complexity increasing per file
==============================
- HardwareObjects/abstract/AbstractOnlineProcessing.py  21
- HardwareObjects/mockup/OnlineProcessingMockup.py  12
- HardwareObjects/DozorOnlineProcessing.py  3
- HardwareObjects/mockup/OfflineProcessingMockup.py  9
- HardwareObjects/queue_model_objects.py  1
         

Clones added
============
- HardwareObjects/abstract/AbstractOnlineProcessing.py  3
- HardwareObjects/DozorOnlineProcessing.py  1
- HardwareObjects/mockup/OfflineProcessingMockup.py  6
         

Clones removed
==============
+ HardwareObjects/queue_entry.py  -1
+ HardwareObjects/EMBL/EMBLOnlineProcessing.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/HardwareRepository/pullRequest?prid=4656946&bid=15596374)

**Pull request merged**
