### PR TITLE
Esrf hutchtrigger

### PR DESCRIPTION
**Pull request by beteva**
Triggering actions to execute when enter/exit hutch. ESRF specific.

### CODE REVIEW

**Review by IvarsKarpics — APPROVED** [review]

**Review by rhfogh — APPROVED** [review]
Looks fine to me - though I cannot really judge it properly

**Comment by marcus-oscarsson** [comment]
It looks like we have a test for python 2.7 that fails and this seems to be due to a previous PR (#590)  @beteva maybe you can have a look, its test/pytest/test_beam.py that fails.

**Comment by marcus-oscarsson** [comment]
Ill merge this PR since its a previous PR that makes the test fail

**Comment by beteva** [comment]
Sorry, no idea why the test are making core dump for python 3.7 Did anybody change the environment?

**Comment by marcus-oscarsson** [comment]
Hm, I dont think so. I guess we just have to run it on one of our machines. We can try that next week if you like

**Pull request merged**
