### PR TITLE
WIP: Updated HardwareObject and related classes as discussed by developers.

### PR DESCRIPTION
**Pull request by rhfogh**
Proposed new HardwareObject class(es) as discussed. I have, of necessity, also done a bit of cleanup on the related abstract classes.

NB, The HardwareObjectMixin is unfortunately necesary. We cannot merge it with anything else because
1) the functionality now in HardwareObject is specific to the xml implementation.
2) The yaml implementation is also used for things that are not HardwareObjects (like Beamline)

For clarification, ConfiguredObject is the equivalent of HardwareObjectNode.

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/HardwareRepository/pullRequest?prid=4707877&bid=15726392)

**Comment by marcus-oscarsson** [comment]
Thanks, looks good to me !, Is this still WIP ?

**Comment by marcus-oscarsson** [comment]
@rhfogh Is this still WIP ?

**Comment by rhfogh** [comment]
@marcus-oscarsson @beteva 

Oh dear - I was convinced I had answered that weeks ago. Af far as I am concerned it is finished, and the next things that should happen is that you should merge it and keep working with it. I have not changed its status, though, because I have not tried to change all the subclasses to make it consistent, so this can not be taken into active branches yet. You could say, I guess, that the work is still progressing, but it is you, not I, who should be progressing it, as discussed.  

Anyway, you have the ball, please merge and continue with the refactoring

Rasmus

**Comment by marcus-oscarsson** [comment]
Okey, thanks for the answer I just did not know what to do with it since it was still WIP, so I will merge this and @beteva will make the changes we discussed and then its back to you again, thats what we said right :) ?

**Comment by rhfogh** [comment]
@marcus-oscarsson 
That is indeed what we said.
Rasmus

**Pull request merged**
